### https://docs.databricks.com/dev-tools/api/latest/index.html
### https://learn.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/aad/service-prin-aad-token#get-token-azure-cli

### Note: First create the managed Databricks workspace!
### Use the script 000_generate_token.sh to generate a Databricks access token. You must be an Admin Account
### Important: Use the Databricks Workspace which was assigned to the Metastore!

@account_id = ********-****-****-****-************
@databricks_instance = adb-****************.*.azuredatabricks.net
@token = 

@databricks_catalog_admins_group_name = <AAD Group Name>
@databricks_catalog_admins_group_id = <AAD Object ID>
@securable_type_metastore = metastore
@full_name_metastore = <Databricks Account Metastore GUID>
@securable_type_catalog = catalog
@full_name_catalog = <Catalog Name>
@securable_type_schema = schema
@full_name_schema = {{full_name_catalog}}.<Schema Name>
@securable_type_storage_credential = storage_credential
@full_name_storage_credential = <Storage Credential Name>
@securable_type_external_location = external_location
@full_name_external_location = <External Location Name>

################################################################
###
### Get Groups
###
################################################################
GET https://{{databricks_instance}}/api/2.0/account/scim/v2/Groups HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Add group
###
################################################################
POST https://{{databricks_instance}}/api/2.0/account/scim/v2/Groups HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "displayName": "{{databricks_catalog_admins_group_name}}",
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:Group"
  ],
  "members": [
    {
      "display": "<Databricks Account Display Name>",
      "value": "<Databricks Account Id>"
    }
  ]
}

################################################################
###
### Delete group
###
################################################################
DELETE https://{{databricks_instance}}/api/2.0/account/scim/v2/Groups/{{databricks_catalog_admins_group_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Grant permissions on Metastore
###
################################################################
PATCH https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_metastore}}/{{full_name_metastore}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "changes" : [
    {
      "principal": "{{databricks_catalog_admins_group_name}}",
      "add": [
        "CREATE_CATALOG",
        "CREATE_EXTERNAL_LOCATION",
        "CREATE_SHARE",
        "CREATE_RECIPIENT",
        "CREATE_PROVIDER"
      ]
    }
  ]
}

################################################################
###
### Get permissions on Metastore
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/effective-permissions/{{securable_type_metastore}}/{{full_name_metastore}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Grant permssions on Catalog
###
################################################################
PATCH https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_catalog}}/{{full_name_catalog}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "changes" : [
    {
      "principal": "{{databricks_catalog_admins_group_name}}",
      "add": [
        "ALL_PRIVILEGES"
      ]
    }
  ]
}

################################################################
###
### Get permissions on Catalog
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/effective-permissions/{{securable_type_catalog}}/{{full_name_catalog}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Grant permissions on Schema
###
################################################################
PATCH https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_schema}}/{{full_name_schema}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "changes" : [
    {
      "principal": "{{databricks_catalog_admins_group_name}}",
      "add": ["ALL_PRIVILEGES"]
    }
  ]
}

################################################################
###
### Get permissions on Schema
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/effective-permissions/{{securable_type_schema}}/{{full_name_schema}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Grant permission on Storage Credential
###
################################################################
PATCH https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_storage_credential}}/{{full_name_storage_credential}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "changes" : [
    {
      "principal": "{{databricks_catalog_admins_group_name}}",
      "add": ["ALL_PRIVILEGES"]
    }
  ]
}

################################################################
###
### Get permissions on Storage Credential
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_storage_credential}}/{{full_name_storage_credential}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Grant permissions on External Location
###
################################################################
PATCH https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_external_location}}/{{full_name_external_location}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "changes" : [
    {
      "principal": "{{databricks_catalog_admins_group_name}}",
      "add": ["ALL_PRIVILEGES"]
    }
  ]
}

################################################################
###
### Get permissions on External Location
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_external_location}}/{{full_name_external_location}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
