### https://docs.databricks.com/dev-tools/api/latest/index.html
### https://learn.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/aad/service-prin-aad-token#get-token-azure-cli
### export CLIENT_ID="********-****-****-****-************"
### export CLIENT_SECRET="****************************************"
### export SUBSCRIPTION_ID="********-****-****-****-************"
### export TENANT_ID="********-****-****-****-************"
### az login --service-principal --username ${CLIENT_ID} --password ${CLIENT_SECRET} --tenant ${TENANT_ID}
### az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d
@account_id = ********-****-****-****-************
@databricks_instance = adb-*******************.azuredatabricks.net
@token = **************************************

### Users
GET https://{{databricks_instance}}/api/2.0/preview/scim/v2/Users HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Service Principals
GET https://{{databricks_instance}}/api/2.0/preview/scim/v2/ServicePrincipals HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Metastores
GET https://{{databricks_instance}}/api/2.1/unity-catalog/metastores HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### External location
GET https://{{databricks_instance}}/api/2.1/unity-catalog/external-locations HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Delete external location
@external_location = *
DELETE https://{{databricks_instance}}/api/2.1/unity-catalog/external-locations/{{external_location}}?force=true HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Storage credential
GET https://{{databricks_instance}}/api/2.1/unity-catalog/storage-credentials HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Delete storage credential
@storage_credentional = *
DELETE https://{{databricks_instance}}/api/2.1/unity-catalog/storage-credentials/{{storage_credentional}}?force=true HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Users
GET https://{{databricks_instance}}/api/2.0/preview/scim/v2/Users HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Groups
GET https://{{databricks_instance}}/api/2.0/preview/scim/v2/Groups HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Groups details
@group_id = *
GET https://{{databricks_instance}}/api/2.0/preview/scim/v2/Groups/{{group_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Service Principals
GET https://{{databricks_instance}}/api/2.0/preview/scim/v2/ServicePrincipals HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Metastores
GET https://{{databricks_instance}}/api/2.1/unity-catalog/metastores HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### External location
GET https://{{databricks_instance}}/api/2.1/unity-catalog/external-locations HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Delete external location
@external_location = *
DELETE https://{{databricks_instance}}/api/2.1/unity-catalog/external-locations/{{external_location}}?force=true HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Storage credential
GET https://{{databricks_instance}}/api/2.1/unity-catalog/storage-credentials HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Delete storage credential
@storage_credentional = *
DELETE https://{{databricks_instance}}/api/2.1/unity-catalog/storage-credentials/{{storage_credentional}}?force=true HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
### Databricks account console
###

### Databricks account console, users
GET https://{{databricks_instance}}/api/2.0/account/scim/v2/Users HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Databricks account console, user
@user_id = *
GET https://{{databricks_instance}}/api/2.0/account/scim/v2/Users/{{user_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Databricks account console, service principals
GET https://{{databricks_instance}}/api/2.0/account/scim/v2/ServicePrincipals HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Databricks account console, service principal
@service_principal = *
GET https://{{databricks_instance}}/api/2.0/account/scim/v2/ServicePrincipals/{{@service_principal}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Databricks account console, service principal (patch)
PATCH https://{{databricks_instance}}/api/2.0/account/scim/v2/ServicePrincipals/{{service_principal}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "replace",
      "path": "roles",
      "value": [
        {
          "value": "account_admin"
        }
      ]
    }
  ]
}

### Databricks account console, groups
GET https://{{databricks_instance}}/api/2.0/account/scim/v2/Groups HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Databricks account console, group
@group_id = *
GET https://{{databricks_instance}}/api/2.0/account/scim/v2/Groups/{{group_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Databricks account console, add group
POST https://{{databricks_instance}}/api/2.0/account/scim/v2/Groups HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "displayName": "Account admins",
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:Group"
  ],
  "members": [
  ]
}

### Databricks account console, patch group
@group_id = *
PATCH https://{{databricks_instance}}/api/2.0/account/scim/v2/Groups/{{group_id}}
content-type: application/json
Authorization: Bearer {{token}}

{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "replace",
      "path": "roles",
      "value": [
        {
          "value": "account_admin"
        }
      ]
    }
  ]
}

### Databricks account console, add user
@group_id = *
@user_id = *
PATCH https://{{databricks_instance}}/api/2.0/account/scim/v2/Groups/{{group_id}}
content-type: application/json
Authorization: Bearer {{token}}

{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "add",
      "value": {
        "members": [
          {
            "value": "{{user_id}}"
          }
        ]
      }
    }
  ]
}

### Databricks account console, list catalogs
GET https://{{databricks_instance}}/api/2.1/unity-catalog/catalogs HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Databricks account console, get catalog
@catalog_name = my_catalog
GET https://{{databricks_instance}}/api/2.1/unity-catalog/catalogs/{{catalog_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### https://docs.databricks.com/api/azure/workspace/grants/get
### Databricks account console, get permissions
@securable_type = *
@full_name = *
GET https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type}}/{{full_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
