### https://docs.databricks.com/dev-tools/api/latest/index.html
### https://learn.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/aad/service-prin-aad-token#get-token-azure-cli

### Note: First create the managed Databricks workspace!
### Use the script 000_generate_token.sh to generate a Databricks access token. You must be an Admin Account

################################################################
###
### Variables
###
################################################################
@account_id = ********-****-****-****-************
@databricks_instance = adb-****************.*.azuredatabricks.net
@token = 
@catalog_name = <Catalog Name>
@external_location = <External Location Name>
@storage_credential = <Storage Credential Name>

################################################################
###
### Get users
###
################################################################
GET https://{{databricks_instance}}/api/2.0/account/scim/v2/Users HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Get groups
###
################################################################
GET https://{{databricks_instance}}/api/2.0/account/scim/v2/Groups HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Get service principals
###
################################################################
GET https://{{databricks_instance}}/api/2.0/account/scim/v2/ServicePrincipals HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Get metastores
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/metastores HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Get catalogs
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/catalogs HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Get catalog details
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/catalogs/{{catalog_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Get external locations
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/external-locations HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Delete external location
###
################################################################
DELETE https://{{databricks_instance}}/api/2.1/unity-catalog/external-locations/{{external_location}}?force=true HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Get storage credentials
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/storage-credentials HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Delete storage credential
###
################################################################
DELETE https://{{databricks_instance}}/api/2.1/unity-catalog/storage-credentials/{{storage_credential}}?force=true HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
