### https://docs.databricks.com/dev-tools/api/latest/index.html
### https://learn.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/aad/service-prin-aad-token#get-token-azure-cli

### Note: First create the managed Databricks workspace!
### Use the script 000_generate_token.sh to generate a Databricks access token. You must be an Admin Account
### Important: Use the Databricks Workspace which was assigned to the Metastore!

################################################################
###
### Variables
###
################################################################
@account_id = ********-****-****-****-************
@databricks_instance = adb-****************.*.azuredatabricks.net
@token = 

@databricks_catalog_admins_group_name = <AAD Group Name>
@databricks_catalog_admins_group_id = <AAD Object ID>
@metastore_id = <Databricks Account Metastore GUID>
@catalog_name = <Catalog Name>
@schema_name = {{catalog_name}}.<Schema Name>
@storage_credential_name = <Storage Credential Name>
@external_location_name = <External Location Name>

################################################################
###
### Constants
###
################################################################
@securable_type_metastore = metastore
@securable_type_catalog = catalog
@securable_type_schema = schema
@securable_type_storage_credential = storage_credential
@securable_type_external_location = external_location

################################################################
###
### Get groups
###
################################################################
GET https://{{databricks_instance}}/api/2.0/account/scim/v2/Groups HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Add group
###
################################################################
POST https://{{databricks_instance}}/api/2.0/account/scim/v2/Groups HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "displayName": "{{databricks_catalog_admins_group_name}}",
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:Group"
  ],
  "members": [
    {
      "display": "<Databricks Account Display Name>",
      "value": "<Databricks Account Id>"
    }
  ]
}

################################################################
###
### Delete group
###
################################################################
DELETE https://{{databricks_instance}}/api/2.0/account/scim/v2/Groups/{{databricks_catalog_admins_group_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Grant permissions on metastore
###
################################################################
PATCH https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_metastore}}/{{metastore_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "changes" : [
    {
      "principal": "{{databricks_catalog_admins_group_name}}",
      "add": [
        "CREATE_CATALOG",
        "CREATE_EXTERNAL_LOCATION",
        "CREATE_SHARE",
        "CREATE_RECIPIENT",
        "CREATE_PROVIDER"
      ]
    }
  ]
}

################################################################
###
### Get permissions on metastore
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/effective-permissions/{{securable_type_metastore}}/{{metastore_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Grant permssions on catalog
###
################################################################
PATCH https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_catalog}}/{{catalog_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "changes" : [
    {
      "principal": "{{databricks_catalog_admins_group_name}}",
      "add": [
        "ALL_PRIVILEGES"
      ]
    }
  ]
}

################################################################
###
### Get permissions on catalog
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/effective-permissions/{{securable_type_catalog}}/{{catalog_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Grant permissions on schema
###
################################################################
PATCH https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_schema}}/{{schema_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "changes" : [
    {
      "principal": "{{databricks_catalog_admins_group_name}}",
      "add": ["ALL_PRIVILEGES"]
    }
  ]
}

################################################################
###
### Get permissions on schema
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/effective-permissions/{{securable_type_schema}}/{{schema_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Grant permission on storage credential
###
################################################################
PATCH https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_storage_credential}}/{{storage_credential_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "changes" : [
    {
      "principal": "{{databricks_catalog_admins_group_name}}",
      "add": ["ALL_PRIVILEGES"]
    }
  ]
}

################################################################
###
### Get permissions on storage credential
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_storage_credential}}/{{storage_credential_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Grant permissions on external location
###
################################################################
PATCH https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_external_location}}/{{external_location_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "changes" : [
    {
      "principal": "{{databricks_catalog_admins_group_name}}",
      "add": ["ALL_PRIVILEGES"]
    }
  ]
}

################################################################
###
### Get permissions on external location
###
################################################################
GET https://{{databricks_instance}}/api/2.1/unity-catalog/permissions/{{securable_type_external_location}}/{{external_location_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
