### https://docs.databricks.com/dev-tools/api/latest/index.html
### https://learn.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/aad/service-prin-aad-token#get-token-azure-cli

### Note: First create the managed Databricks workspace!
### Use the script 000_generate_token.sh to generate a Databricks access token. You must be an Admin Account

################################################################
###
### Variables
###
################################################################
@account_id = ********-****-****-****-************
@databricks_instance = adb-****************.*.azuredatabricks.net
@token = 

@user_id = <Databricks User Id>
@group_id = <Databricks Group Id>
@service_principal_id = <Databricks Service Principal Id>

################################################################
###
### Get users
###
################################################################
GET https://{{databricks_instance}}/api/2.0/preview/scim/v2/Users HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Get users details
###
################################################################
GET https://{{databricks_instance}}/api/2.0/preview/scim/v2/Users/{{user_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Get groups
###
################################################################
GET https://{{databricks_instance}}/api/2.0/preview/scim/v2/Groups HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Get group details
###
################################################################
GET https://{{databricks_instance}}/api/2.0/preview/scim/v2/Groups/{{group_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Get service principals
###
################################################################
GET https://{{databricks_instance}}/api/2.0/preview/scim/v2/ServicePrincipals HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

################################################################
###
### Get service principal details
###
################################################################
GET https://{{databricks_instance}}/api/2.0/preview/scim/v2/ServicePrincipals/{{service_principal_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
